### PR TITLE
Better buffer reuse

### PR DESCRIPTION
**Pull request by bkw**
here is the proper fix for #1 based on your idea (refilling the buffer from the right).
Along the way I found the reason for my buffer corruption; Reader.buffer returns a copy now, not a slice that my harm the internal buffer when messed with.

### CODE REVIEW

**Comment by felixge** [comment]
Looks good. Before I merge, two things:
- Can you remove the change to `buffer()`? IMO that's a separate issue, and I actually disagree with this choice. I want buffy to be fast enough so I can later on use it in node-mysql, this means an implicit copy is not a desirable default for me. (That being said, we can discuss it in a separate issue if u disagree).
- I'm not sure if the re-filling of the current buffer is handled correctly in your patch. It seems like you don't update `this._offset`, but I'm confused on how that would work. (I may be wrong as I need to actually try this patch, but if you could have a look yourself first that'd be great).

Thanks for the help!

**Comment by bkw** [comment]
No problem will do.

The buffer() thing bit me with decoding the video frames. Since it's just a pointer to the same memory region, the next update to the private _buffer of buffy will actually change the data it returned to you before. Felt very wrong for me, prone to timing bugs.
But no problem, can I just create another method, say bytes() that behaves more like the other methods?

I'm pretty certain the refilling of the buffer is correct. When we reuse the buffer, we decrement the offset by the length of the new buffer, since thats how far the contents will be pushed "left".
Line 31:

```
this._offset -= newBuffer.length;
```

Also only with this code (and the changes to buffer()) could I get the same output from a recorded drone-stream as with buffy-0.0.2.

So, my proposal: I make buffer() behave as before and introduce a new method bytes() that does what I made buffer() do before, namely advance the offset and return a copy of the bytes rewquested.

Cool?

**Comment by bkw** [comment]
So when buffy was fast enough for node-mysql without the copy in buffer() but with an expensive copy (Buffer.concat) on every write, maybe we should scrap the whole dynamic buffer-resizing thing then?
I suspect you just did not see any side effects from slice() since you generated a unique buffer on every write anyway with buffy-0.0.2. Could that be the case?

**Comment by felixge** [comment]
> The buffer() thing bit me with decoding the video frames. Since it's just a pointer to the same memory region, the next update to the private _buffer of buffy will actually change the data it returned to you before. Felt very wrong for me, prone to timing bugs.

Ohhh ... stupid me. Yes, that is a terrible default behavior. I didn't think of this. Your fix makes sense. But it should be a separate pull request - can you split it up? (I can do it if not)

> So when buffy was fast enough for node-mysql without the copy in buffer() but with an expensive copy (Buffer.concat) on every write, maybe we should scrap the whole dynamic buffer-resizing thing then?
> I suspect you just did not see any side effects from slice() since you generated a unique buffer on every write anyway with buffy-0.0.2. Could that be the case?

I have not used buffy for anything except the ar-drone lib yet - but I have benchmarked a naive Buffer.concat() approach vs. the buffer re-use trickery, and the buffer re-use trickery provided significant performance benefits. Having the `copy()` will actually not be a performance issue for node-mysql as it doesn't use this operation for anything but binary fields.

So yeah, can you turn this into two pulls or commits? Then I'll merge.

--fg

**Comment by bkw** [comment]
More PRs coming up. After coffee ;-)

**Comment by bkw** [comment]
continued in #3 and #4

**Pull request closed without merging**
